name: sam_remastered
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  qr_flutter: ^4.1.0
  google_fonts: ^8.0.0
  google_maps_flutter: ^2.14.2
  google_maps_flutter_android: ^2.19.0
  google_maps_flutter_platform_interface: ^2.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Importante: Esto habilita la carpeta de imÃ¡genes para el carrusel
  assets:
    - assets/images/